#!/usr/bin/env node
/**
 * Builds the Reddit copy of the game from the files in the repository root.
 *
 *  - public/game.html   : index.html with Google Fonts replaced by self-hosted
 *                         fonts (the Reddit webview allows no external requests)
 *                         and the backend bridge loaded before game.js
 *  - public/style.css   : copied verbatim
 *  - public/game.js     : copied verbatim
 *  - public/devvit-bridge.js
 *  - public/fonts/*.woff2 + public/fonts.css : Fredoka and Nunito from @fontsource
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, '..');
const rootDir = resolve(appDir, '..');
const publicDir = join(appDir, 'public');
const fontsDir = join(publicDir, 'fonts');

const need = (p) => {
  if (!existsSync(p)) throw new Error(`missing ${p}`);
  return p;
};

mkdirSync(fontsDir, { recursive: true });

// 1. Fonts from @fontsource packages (installed as devDependencies)
const FONTS = [
  { family: 'Fredoka', pkg: '@fontsource/fredoka', weights: [400, 500, 600, 700] },
  { family: 'Nunito', pkg: '@fontsource/nunito', weights: [400, 600, 700, 800] },
];
let fontCss = '/* Self-hosted fonts for the Reddit build (generated by scripts/sync.mjs) */\n';
for (const font of FONTS) {
  const filesDir = need(join(appDir, 'node_modules', font.pkg, 'files'));
  for (const weight of font.weights) {
    const file = `${font.family.toLowerCase()}-latin-${weight}-normal.woff2`;
    copyFileSync(need(join(filesDir, file)), join(fontsDir, file));
    fontCss += `@font-face{font-family:'${font.family}';font-style:normal;font-weight:${weight};font-display:swap;src:url(fonts/${file}) format('woff2');}\n`;
  }
}
writeFileSync(join(publicDir, 'fonts.css'), fontCss);

// 2. game.html from the root index.html
let html = readFileSync(need(join(rootDir, 'index.html')), 'utf8');
const before = html;
html = html
  .replace(/\s*<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com" \/>/, '')
  .replace(/\s*<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com" crossorigin \/>/, '')
  .replace(/<link href="https:\/\/fonts\.googleapis\.com\/css2[^"]*" rel="stylesheet" \/>/, '<link rel="stylesheet" href="fonts.css" />')
  .replace('<script src="game.js"></script>', '<script src="devvit-bridge.js"></script>\n  <script src="game.js"></script>');
if (html === before || /fonts\.googleapis|fonts\.gstatic/.test(html) || !html.includes('devvit-bridge.js')) {
  throw new Error('index.html did not look as expected; update scripts/sync.mjs');
}
writeFileSync(join(publicDir, 'game.html'), html);

// 3. Verbatim copies
copyFileSync(need(join(rootDir, 'style.css')), join(publicDir, 'style.css'));
copyFileSync(need(join(rootDir, 'game.js')), join(publicDir, 'game.js'));
copyFileSync(need(join(appDir, 'src', 'client', 'devvit-bridge.js')), join(publicDir, 'devvit-bridge.js'));

console.log('synced game into reddit/public (game.html, style.css, game.js, devvit-bridge.js, fonts)');
